"""Add Staff Position

Revision ID: 56ea4907a8f4
Revises: 
Create Date: 2022-12-02 08:53:41.894216

"""
import sqlalchemy_utils
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "56ea4907a8f4"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "position",
        sa.Column("pk", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(length=50), nullable=False),
        sa.Column("detail", sa.String(length=255), nullable=False),
        sa.PrimaryKeyConstraint("pk"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "staff",
        sa.Column("pk", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("hiring_date", sa.DateTime(), nullable=True),
        sa.Column("last_name", sa.String(length=50), nullable=False),
        sa.Column("first_name", sa.String(length=50), nullable=False),
        sa.Column("middle_name", sa.String(length=50), nullable=False),
        sa.Column("wage_rate", sa.DECIMAL(precision=10, scale=2), nullable=False),
        sa.Column("path", sqlalchemy_utils.types.ltree.LtreeType(), nullable=False),
        sa.Column("position_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["position_id"],
            ["position.pk"],
        ),
        sa.PrimaryKeyConstraint("pk"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("staff")
    op.drop_table("position")
    # ### end Alembic commands ###
