version: "3.9"

networks:
  app-network-test:

services:
  pg_db-test:
    image: postgres:15.1
    container_name: pg_name-test
    restart: always
    environment:
      POSTGRES_DB: "postgres_test"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      PGDATA: "/var/lib/postgresql/data/pg_data"
    ports:
      - "54320:5432"
    networks:
      - app-network-test

  app-test:
    build:
      context: .
    depends_on:
      - pg_db-test
    container_name: app-backend-test
    command: sh -c "python main.py"
    volumes:
      - ./app:/app
    ports:
      - "9000:8000"
    tty: true
    stdin_open: true
    restart: always
    networks:
      - app-network-test
    environment:
      DB_URL: "postgresql+asyncpg://postgres:postgres@pg_db-test/postgres_test"
      PORT: 9000
      PYTHONPATH: "/app"
      DEBUG: "0"
